sensor:
    laser:
        valid_distance: 15    # 激光的有效距离 
# 传感器外参
extrinsic:
  odom: 
    prime_laser: 
      upside_down: false  # 倒置 
      level: [0, 0, 0]   # 主激光雷达 - odom的外参  x,y,theta

# 栅格地图多分辨率金字塔   
grid_map_pyramid:
  bottom_resolution: 0.05
  map_size:    # 真实的物理尺寸  单位 m
      x: 40
      y: 40
  map_depth: 3 # 金子塔层数
  grid_update_method: "probability"   # 计数法 cnt     概率法  probability

kalman_filter:   
  type: "ekf"     # ekf / eskf
  coordinate: "globalcentric"     # 参考坐标系  globalcentric / robocentric
  enable: false

          
